### ISSUE TITLE
"Called id for nil" when setting nil parent

### ISSUE THREAD

**Issue by steveh** [svenfuchs/simple_nested_set#4]
Reproduction:

```
klass.create!(:name => "Test", :parent => nil)
```

Error:

```
Called id for nil, which would mistakenly be 4 -- if you really wanted the id of nil, use object_id
/Users/steve/.rvm/gems/ruby-1.9.2-p0/gems/simple_nested_set-0.0.19/lib/simple_nested_set/move/by_attributes.rb:75:in `block in normalize_attributes!'
/Users/steve/.rvm/gems/ruby-1.9.2-p0/gems/simple_nested_set-0.0.19/lib/simple_nested_set/move/by_attributes.rb:74:in `each'
/Users/steve/.rvm/gems/ruby-1.9.2-p0/gems/simple_nested_set-0.0.19/lib/simple_nested_set/move/by_attributes.rb:74:in `normalize_attributes!'
/Users/steve/.rvm/gems/ruby-1.9.2-p0/gems/simple_nested_set-0.0.19/lib/simple_nested_set/move/by_attributes.rb:12:in `initialize'
/Users/steve/.rvm/gems/ruby-1.9.2-p0/gems/simple_nested_set-0.0.19/lib/simple_nested_set/nested_set.rb:107:in `new'
/Users/steve/.rvm/gems/ruby-1.9.2-p0/gems/simple_nested_set-0.0.19/lib/simple_nested_set/nested_set.rb:107:in `move_by_attributes'
/Users/steve/.rvm/gems/ruby-1.9.2-p0/gems/simple_nested_set-0.0.19/lib/simple_nested_set/nested_set.rb:44:in `save!'
/Users/steve/.rvm/gems/ruby-1.9.2-p0/gems/simple_nested_set-0.0.19/lib/simple_nested_set/act_macro.rb:16:in `block in acts_as_nested_set'
/Users/steve/.rvm/gems/ruby-1.9.2-p0/gems/activesupport-3.0.1/lib/active_support/callbacks.rb:425:in `_run_save_callbacks'
/Users/steve/.rvm/gems/ruby-1.9.2-p0/gems/activerecord-3.0.1/lib/active_record/callbacks.rb:277:in `create_or_update'
/Users/steve/.rvm/gems/ruby-1.9.2-p0/gems/activerecord-3.0.1/lib/active_record/persistence.rb:56:in `save!'
/Users/steve/.rvm/gems/ruby-1.9.2-p0/gems/activerecord-3.0.1/lib/active_record/validations.rb:49:in `save!'
/Users/steve/.rvm/gems/ruby-1.9.2-p0/gems/activerecord-3.0.1/lib/active_record/attribute_methods/dirty.rb:30:in `save!'
/Users/steve/.rvm/gems/ruby-1.9.2-p0/gems/activerecord-3.0.1/lib/active_record/transactions.rb:242:in `block in save!'
/Users/steve/.rvm/gems/ruby-1.9.2-p0/gems/activerecord-3.0.1/lib/active_record/transactions.rb:289:in `block in with_transaction_returning_status'
/Users/steve/.rvm/gems/ruby-1.9.2-p0/gems/activerecord-3.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:139:in `transaction'
/Users/steve/.rvm/gems/ruby-1.9.2-p0/gems/activerecord-3.0.1/lib/active_record/transactions.rb:204:in `transaction'
/Users/steve/.rvm/gems/ruby-1.9.2-p0/gems/activerecord-3.0.1/lib/active_record/transactions.rb:287:in `with_transaction_returning_status'
/Users/steve/.rvm/gems/ruby-1.9.2-p0/gems/activerecord-3.0.1/lib/active_record/transactions.rb:242:in `save!'
/Users/steve/.rvm/gems/ruby-1.9.2-p0/gems/activerecord-3.0.1/lib/active_record/validations.rb:34:in `create!'
/Users/steve/Sites/localist/db/seeds.rb:72:in `block in recursively_create_tree'
```

Workaround:

Don't call `#create` with `parent => nil`

Fix:

Add `&& attributes[key]` to line 75 of `lib/simple_nested_set/move/by_attributes.rb`

**Comment by kronn** [comment]
Thanks for the detailed error report. I'll look into it.

**Comment by kronn** [comment]
the bug should be fixed, i think sven will publish the updated gem before i write this comment. :)

Thanks again for your report.
